// FrontEndAngular/src/app/content/book-details/book-details.component.ts
import { Component, OnInit } from '@angular/core';
import { BooksService } from 'src/app/services/books.service';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-book-details',
  templateUrl: './book-details.component.html',
  styleUrls: ['./book-details.component.css']
})
export class BookDetailsComponent implements OnInit {
  book;
  bookId;
  constructor(private bookDetails: BooksService, private route: ActivatedRoute) { }

  ngOnInit(): void {

    this.route.params.subscribe(params => {
      this.bookId = params['id'];
    })

    this.bookDetails.getBookById(this.bookId).subscribe(response =>{
      this.book = response;
    })
  }

}

<div style="margin-top: 2%">
    <div class="container-fluid">
        <div class="row margin">
            <div class="col-md-8 offset-md-2">

                <div class="d-flex justify-content-start">
                    <img src={{book?.image}}
                        height="150" width="100">
                    <div class="d-flex flex-column book">
                        <div> Numele cartii: {{book?.name}}</div>
                        <div> Autor: {{book?.author}}</div>
                        <div> Data publicarii: {{book?.date | date:"yyyy-MM-dd"}}</div>
                        <div> Gen: {{book?.genre}}</div>
                        <div> Numar exemplare disponibile: {{book?.free}}</div>
                    </div>
                </div>
                <div>Description: {{book?.description}}</div>
            </div>
        </div>
    </div>
</div>

// frontend_react/src/componets/book-details.js
import React from "react";
import { getBookById } from "../services/bookService";

class BookDetails extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      error: null,
      isLoaded: false,
      bookInfo: [],
    };
  }

  componentDidMount() {
    getBookById(this.props.match.params.id).then(
      (result) => {
        this.setState({
          isLoaded: true,
          bookInfo: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  render() {
    const { error, isLoaded, bookInfo } = this.state;
    if (error) {
      return <div>Error: {error.message}</div>;
    } else if (!isLoaded) {
      return <div>Loading...</div>;
    } else {
      return (
        <div className="container-fluid page-up-margin">
          <div className="row">
            <div className="col-md-8 offset-md-2">
              <div className="d-flex justify-content-start">
                <img src={bookInfo.image} height="150" width="100" />
                <div className="d-flex flex-column book text-format">
                  <div> Numele cartii: {bookInfo?.name}</div>
                  <div> Autor: {bookInfo.author}</div>
                  <div> Data publicarii: {bookInfo.date}</div>
                  <div> Gen: {bookInfo.genre}</div>
                  <div> Numar exemplare disponibile: {bookInfo.free}</div>
                </div>
              </div>
              <div>Descriere: {bookInfo.description}</div>
            </div>
          </div>
        </div>
      );
    }
  }
}

export default BookDetails;
