// FrontEndAngular/src/app/content/books/book-edit/book-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { GenresService } from 'src/app/services/genres.service';
import { BooksService } from 'src/app/services/books.service';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-book-edit',
  templateUrl: './book-edit.component.html',
  styleUrls: ['./book-edit.component.css']
})
export class BookEditComponent implements OnInit {
  bookId;
  data;

  genres;

  name;
  author;
  date;
  bookGenre;
  total;
  isbn;
  description;
  image;
  constructor(private genre: GenresService, private book: BooksService, private route:ActivatedRoute, private router:Router) { }

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.bookId = params['id'];
    })

    this.genre.getGenres().subscribe(response=>{
      this.genres =response;
    })

    this.book.getBookById(this.bookId).subscribe(response=>{
      this.data = response;
      this.name = this.data.name;
      this.author = this.data.author;
      this.date = this.data.date;
      this.bookGenre = this.data.genre;
      this.total = this.data.total;
      this.isbn = this.data.isbn;
      this.description = this.data.description;
      this.image = this.data.image;
    })

  }

  submit(form){
    this.book.editBookById(this.bookId, {name: form.value.name, author: form.value.author, date: form.value.date, genre: form.value.genre, description: form.value.description, isbn: form.value.isbn, total: form.value.total, image: form.value.image}).subscribe(
      res=>{this.router.navigate(['../../../books'])},
      err=>{}
    )
    console.log(form.value);
  }

}

<div style="margin-top: 2%">
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-6 offset-md-3">

<form #form="ngForm" (ngSubmit)="submit(form)">
    <div class="form-group ">
        <label for="name">Nume-editare</label>
        <input 
            required 
            minlength="5" 
            [(ngModel)] = "name"
            name="name" 
            id="name" 
            type="text" 
            class="form-control input-md">
    </div>

    <div class="form-group">
        <label for="author">Autor</label>
        <input 
            required 
            minlength="2" 
            [(ngModel)] = "author"
            name="author" 
            type="text"
            id="author" 
            class="form-control input-md">
    </div>

    <div class="form-group">
        <label for="date">Data</label>
        <input 
            required 
            minlength="2" 
            [(ngModel)] = "date"
            name="date" 
            type="text"
            id="date" 
            class="form-control input-md">
    </div>

    <div class="form-group">
        <label for="genre">Gen</label>
        <select [(ngModel)] = "bookGenre" name="genre" id="genre" class="custom-select" >
            <option value="" disabled>Alege genul</option>
            <option *ngFor="let genre of genres">{{genre}}</option>
         </select>
    </div>

    <div class="form-group">
        <label for="total">Nr Exemplare</label>
        <input 
            required 
            minlength="2" 
            [(ngModel)] = "total"
            name="total" 
            type="number"
            id="total" 
            class="form-control input-md">
    </div>

    <div class="form-group">
        <label for="isbn">ISBN</label>
        <input 
            required 
            minlength="2" 
            [(ngModel)] = "isbn"
            name="isbn" 
            type="number"
            id="isbn" 
            class="form-control input-md">
    </div>

    <div class="form-group">
        <label for="description">Descriere</label>
        <input 
            required 
            minlength="2" 
            [(ngModel)] = "description"
            name="description" 
            type="text"
            id="description" 
            class="form-control input-md">
    </div>

    <div class="form-group">
        <label for="image">Imagine</label>
        <input 
            required 
            minlength="2" 
            [(ngModel)] = "image"
            name="image" 
            type="text"
            id="image" 
            class="form-control input-md">
    </div>

    <div class="text-center">
        <button class="btn btn-primary">
            Submit
        </button>
    </div>
</form>
</div></div></div></div>

// frontend_react/src/componets/book-edit.js
import React from "react";
import "./book-add.css";
import { getGenres } from "../services/genreService";
import { getBookById, editBookById } from "../services/bookService";

class BookEdit extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      name: "",
      author: "",
      date: "",
      genres: [],
      selectedGenre: "",
      bookTotal: 0,
      isbn: 0,
      description: "",
      image: "",
    };

    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  componentDidMount() {
    getBookById(this.props.match.params.id).then(
      (result) => {
        console.log(result.author);
        this.setState({
          isLoaded: true,
          name: result.name,
          author: result.author,
          date: result.date,
          selectedGenre: result.genre,
          bookTotal: result.total,
          isbn: result.isbn,
          description: result.description,
          image: result.image,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );

    getGenres().then(
      (result) => {
        console.log(this.props.match.params.id);
        console.log(result);
        this.setState({
          isLoaded: true,
          genres: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  handleChange(event) {
    const target = event.target;
    const value = target.value;
    const name = target.name;
    this.setState({ [name]: value });
  }

  handleSubmit(event) {
    editBookById(this.props.match.params.id, {
      name: this.state.name,
      author: this.state.author,
      date: this.state.date,
      genre: this.state.selectedGenre,
      description: this.state.description,
      isbn: this.state.isbn,
      total: this.state.bookTotal,
      image: this.state.image,
    }).then((result) => {
      this.props.history.push("/books");
    });
    event.preventDefault();
  }

  render() {
    return (
      <div className="container-fluid page-up-margin">
        <div className="row">
          <div className="col-md-2 offset-md-5">
            <form onSubmit={this.handleSubmit}>
              <div className="form-group">
                <label>
                  Nume:
                  <input
                    type="text"
                    name="name"
                    value={this.state.name}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
              </div>
              <div className="form-group">
                <label>
                  Autor:
                  <input
                    type="text"
                    name="author"
                    value={this.state.author}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
              </div>
              <div className="form-group">
                <label>
                  Data:
                  <input
                    type="text"
                    name="date"
                    value={this.state.date}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
                <label>
                  Gen:
                  <select
                    value={this.state.selectedGenre}
                    onChange={this.handleChange}
                    name="selectedGenre"
                    className="form-control input-md"
                  >
                    <option value="" disabled>
                      Alege genul
                    </option>
                    {this.state.genres.map((genre) => (
                      <option value={genre}>{genre}</option>
                    ))}
                  </select>
                </label>
                <label>
                  Nr Exemplare:
                  <input
                    type="text"
                    name="bookTotal"
                    value={this.state.bookTotal}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
                <label>
                  ISBN:
                  <input
                    type="text"
                    name="isbn"
                    value={this.state.isbn}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
                <label>
                  Descriere:
                  <input
                    type="description"
                    name="date"
                    value={this.state.description}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
                <label>
                  Imagine:
                  <input
                    type="text"
                    name="image"
                    value={this.state.image}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
              </div>
              <div className="text-center">
                <input
                  type="submit"
                  value="Trimite"
                  className="btn btn-primary"
                />
              </div>
            </form>
          </div>
        </div>
      </div>
    );
  }
}

export default BookEdit;
