// FrontEndAngular/src/app/content/books/book-borrow/book-borrow.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from "@angular/core";
import { UsersService } from "src/app/services/users.service";
import { BooksService } from "src/app/services/books.service";
import { ActivatedRoute } from "@angular/router";

@Component({
  selector: "app-book-borrow",
  templateUrl: "./book-borrow.component.html",
  styleUrls: ["./book-borrow.component.css"],
})
export class BookBorrowComponent implements OnInit {
  @Input() id: string;
  @Input() maxSize: number;
  @Output() pageChange: EventEmitter<number>;
  @Output() pageBoundsCorrection: EventEmitter<number>;

  bookId;
  tableUsers;
  bookName;

  users;
  pageNr: number = 1;
  totalNr: number;
  message: string = "";
  constructor(
    private user: UsersService,
    private bookDetails: BooksService,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe((params) => {
      this.bookId = params["id"];
    });
    this.getBookData();
  }
  async getBookData() {
    this.bookName = await this.bookDetails.getBookById(this.bookId).toPromise();
    this.getUserData();
    this.getUserFree();
  }

  getUserData() {
    this.user.getUserTable(this.bookName?.name).subscribe((response) => {
      this.tableUsers = response;
    });
  }

  getUserFree() {
    this.user
      .getUserFree(this.pageNr, this.message, this.bookName?.name)
      .subscribe((response) => {
        this.users = response;
        this.totalNr = 0;
        if (Object.keys(response).length) {
          this.totalNr = response[0].total;
        }
      });
  }

  addUserBook(id) {
    this.user.addUserBook({ book: this.bookName?.name }, id).subscribe(
      (res) => {
        this.getUserData();
        this.getUserFree();
        this.editBookCountUp();
      },
      (err) => {}
    );
  }

  receiveMessage($event) {
    this.message = $event;
    this.pageNr = 1;
    this.getUserFree();
  }

  getPageInfo(nr: number) {
    this.pageNr = nr;
    this.getUserFree();
  }

  deleteUserBook(id) {
    this.user.deleteUserBook(id, this.bookName?.name).subscribe(
      (res) => {
        this.getUserData();
        this.getUserFree();
        this.editBookCountDown();
      },
      (err) => {}
    );
  }

  editBookCountUp() {
    this.bookDetails.editBookCountUp(this.bookId, {}).subscribe(
      (res) => {},
      (err) => {}
    );
  }
  editBookCountDown() {
    this.bookDetails.editBookCountDown(this.bookId, {}).subscribe(
      (res) => {},
      (err) => {}
    );
  }
}

<div style="margin-top: 2%;">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4 offset-md-2">
        <app-search (messageEvent)="receiveMessage($event)"></app-search>
        <div>
          <table class="table">
            <thead class="thead-light">
              <th>Nume</th>
              <th>CNP</th>
              <th>Optiuni</th>
            </thead>
            <tbody class="text-format">
              <tr
                *ngFor="
                  let user of users
                    | paginate
                      : {
                          itemsPerPage: 7,
                          currentPage: pageNr,
                          totalItems: totalNr
                        }
                "
              >
                <td>{{ user.name }}</td>
                <td>{{ user.cnp }}</td>
                <td>
                  <button
                    type="button"
                    class="btn btn-sm btn-success inner_button"
                    id="add"
                    (click)="addUserBook(user.id)"
                  >
                    <i class="fas fa-plus"></i>
                  </button>
                </td>
              </tr>
            </tbody>
          </table>

          <pagination-template
            #p="paginationApi"
            (pageChange)="pageChange?.emit($event)"
            class="pagination justify-content-end"
          >
            <div
              class="pagination-previous page-item"
              [class.disabled]="p.isFirstPage()"
            >
              <a
                class="page-link"
                *ngIf="!p.isFirstPage()"
                (click)="p.previous(); getPageInfo(pageNr - 1)"
              >
                Inapoi
              </a>
            </div>

            <div
              *ngFor="let page of p.pages; &quot;page-item&quot;"
              [class.current]="p.getCurrent() === page.value"
            >
              <a
                class="page-link"
                (click)="p.setCurrent(page.value); getPageInfo(page.value)"
                *ngIf="p.getCurrent() !== page.value"
              >
                <span class="page-item">{{ page.label }}</span>
              </a>
              <div *ngIf="p.getCurrent() === page.value">
                <span class="page-item active page-link">{{ page.label }}</span>
              </div>
            </div>

            <div
              class="pagination-next page-item"
              [class.disabled]="p.isLastPage()"
            >
              <a
                class="page-link"
                *ngIf="!p.isLastPage()"
                (click)="p.next(); getPageInfo(pageNr + 1)"
              >
                Inainte
              </a>
            </div>
          </pagination-template>
        </div>
      </div>
      <div class="col-md-4">
        <table class="table">
          <thead class="thead-light">
            <th>Nume</th>
            <th>CNP</th>
            <th>Carte imprumutata</th>
            <th>Optiuni</th>
          </thead>
          <tbody class="text-format">
            <tr *ngFor="let user of tableUsers">
              <td>{{ user.name }}</td>
              <td>{{ user.cnp }}</td>
              <td>{{ bookName?.name }}</td>
              <td>
                <button
                  type="button"
                  class="btn btn-sm btn-danger"
                  id="edit"
                  (click)="deleteUserBook(user.id)"
                >
                  <i class="far fa-trash-alt"></i>
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

// frontend_react/src/componets/book-borrow.js
import React from "react";
import "./users.css";
import {
  getUserTable,
  getUserFree,
  addUserBook,
  deleteUserBook,
} from "../services/userService";
import {
  getBookById,
  editBookCountUp,
  editBookCountDown,
} from "../services/bookService";
import Pagination from "react-js-pagination";

class BookBorrow extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      error: null,
      isLoaded: false,
      freeUsers: [],
      usedUsers: [],
      book: {},
      filter: "",
      activePage: 1,
      totalPages: 0,
    };
    this.AddButtonCLicked = this.AddButtonCLicked.bind(this);
    this.DeleteButtonClicked = this.DeleteButtonClicked.bind(this);
    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  async componentDidMount() {
    await getBookById(this.props.match.params.id).then(
      (result) => {
        console.log("book by id");
        console.log(result);
        this.setState({
          isLoaded: true,
          book: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );

    getUserFree(1, this.state.filter, this.state.book.name).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].total,
          });
        }
        this.setState({
          isLoaded: true,
          freeUsers: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );

    getUserTable(this.state.book.name).then(
      (result) => {
        console.log("user table");
        console.log(this.state.book);
        console.log(result);
        this.setState({
          isLoaded: true,
          usedUsers: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  async AddButtonCLicked(id) {
    await addUserBook({ book: this.state.book.name }, id);
    await editBookCountUp(this.state.book.id, {});
    getUserTable(this.state.book.name).then(
      (result) => {
        this.setState({
          isLoaded: true,
          usedUsers: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );

    getUserFree(1, this.state.filter, this.state.book.name).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].total,
          });
        }
        this.setState({
          isLoaded: true,
          freeUsers: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  async DeleteButtonClicked(id) {
    await deleteUserBook({ book: this.state.book.name }, id);
    await editBookCountDown(this.state.book.id, {});
    getUserFree(1, this.state.filter, this.state.book.name).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].total,
          });
        }
        this.setState({
          isLoaded: true,
          freeUsers: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );

    getUserTable(this.state.book.name).then(
      (result) => {
        this.setState({
          isLoaded: true,
          usedUsers: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  handlePageChange(pageNumber) {
    console.log(`active page is ${pageNumber}`);
    this.setState({ activePage: pageNumber });
    getUserFree(pageNumber, this.state.filter, this.state.book.name).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].total,
          });
        }
        console.log(result);
        this.setState({
          isLoaded: true,
          freeUsers: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  handleChange(event) {
    const target = event.target;
    const value = target.value;
    const name = target.name;
    this.setState({ [name]: value });
  }

  handleSubmit(event) {
    getUserFree(1, this.state.filter, this.state.book.name).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].total,
          });
        }
        console.log(result);
        this.setState({
          isLoaded: true,
          freeUsers: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  render() {
    const { error, isLoaded, freeUsers, book, usedUsers } = this.state;
    if (error) {
      return <div>Error: {error.message}</div>;
    } else if (!isLoaded) {
      return <div>Loading...</div>;
    } else {
      return (
        <div className="page-up-margin">
          <div className="container-fluid">
            <div className="row">
              <div className="col-md-4 offset-md-2">
                <div class="input-group md-form form-sm form-2 pl-0 margin">
                  <input
                    class="form-control my-0 py-1 amber-border"
                    type="text"
                    placeholder="Search"
                    aria-label="Search"
                    name="filter"
                    value={this.state.filter}
                    onChange={this.handleChange}
                  />
                  <div class="input-group-append">
                    <span
                      class="input-group-text amber lighten-3"
                      id="basic-text1"
                    >
                      <i
                        class="fas fa-search"
                        onClick={this.handleSubmit}
                        aria-hidden="true"
                      ></i>
                    </span>
                  </div>
                </div>
                <table className="table">
                  <thead className="thead-light">
                    <th>Nume</th>
                    <th>CNP</th>
                    <th>Opiuni</th>
                  </thead>
                  {freeUsers.map((user) => (
                    <tbody key={user.name} className="text-format">
                      <tr>
                        <td>{user.name} </td>
                        <td>{user.cnp}</td>
                        <td>
                          <button
                            onClick={() => this.AddButtonCLicked(user.id)}
                            type="button"
                            className="btn btn-sm btn-success"
                            id="add"
                          >
                            <i class="fas fa-plus"></i>
                          </button>
                        </td>
                      </tr>
                    </tbody>
                  ))}
                </table>
                <div className="d-flex justify-content-end">
                  <Pagination
                    prevPageText="Inapoi"
                    nextPageText="Inainte"
                    activePage={this.state.activePage}
                    itemsCountPerPage={7}
                    totalItemsCount={this.state.totalPages}
                    onChange={this.handlePageChange.bind(this)}
                  />
                </div>
              </div>
              <div className="col-md-4">
                <table className="table">
                  <thead className="thead-light">
                    <th>Nume</th>
                    <th>CNP</th>
                    <th>Carte imprumutata</th>
                    <th>Opiuni</th>
                  </thead>
                  {usedUsers.map((user) => (
                    <tbody key={user.name} className="text-format">
                      <tr>
                        <td>{user.name} </td>
                        <td>{user.cnp}</td>
                        <td>{book.name}</td>
                        <td>
                          <button
                            onClick={() => this.DeleteButtonClicked(user.id)}
                            type="button"
                            className="btn btn-sm btn-danger"
                            id="delete"
                          >
                            <i class="far fa-trash-alt"></i>
                          </button>
                        </td>
                      </tr>
                    </tbody>
                  ))}
                </table>
              </div>
            </div>
          </div>
        </div>
      );
    }
  }
}

export default BookBorrow;
