// FrontEndAngular/src/app/content/administration/table/table.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { BooksService } from 'src/app/services/books.service';

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']
})
export class TableComponent implements OnInit {
  @Input() id: string;
  @Input() maxSize: number;
  @Output() pageChange: EventEmitter<number>;
  @Output() pageBoundsCorrection: EventEmitter<number>;

  books;
  pageNr: number = 1;
  filter: boolean = true;
  isBook = true;
  isAuthor = false;
  totalPages;

  query = {
    book: true,
    author: false,
    search: '',
    genres: []
  }
  constructor(private book: BooksService) { }

  ngOnInit(): void {
    this.getUserData();
  }

  getPageInfo(nr:number){
    this.pageNr = nr;
    this.getUserData();
  }

  receiveMessage($event) {
    this.query.search = $event;
    
    this.getUserData();
  }

  receiveFilter($event) {
    
    this.filter = $event
    if (this.filter === true){
      this.isBook = true;
      this.isAuthor = false;
    }
    else{
      this.isBook = false;
      this.isAuthor = true;
    }
    this.pageNr = 1;
    this.query.book = this.isBook;
    this.query.author = this.isAuthor;
  }
  getUserData(){
    this.book.getBooks(this.pageNr, this.query.search, this.query.book, this.query.author, this.query.genres).subscribe(response =>{
      this.books = response;
      console.log(this.books)
      this.totalPages =  0;
      if(Object.keys(response).length){
        
        this.totalPages = response[0].count
        console.log(this.totalPages);
      }
    })
  }
}

<div style="margin-top: 2%">
  <div class="container-fluid">
      <div class="row">
          <div class="col-md-8 offset-md-2">
              <app-search (messageEvent)="receiveMessage($event)" (radioEvent)="receiveFilter($event)"></app-search>
          </div>
          <div class="col-md-8 offset-md-2 custyle">
            <table class="table table-striped custab">
              <thead >
          
                      <th>Carte</th>
                      <th>Autor</th>
                      <th>ISBN</th>
                      <th>Exemplare totale</th>
                      <th>Exemplare in uz</th>
                      <th>Detinatori curenti</th>
              </thead>
              <tr *ngFor="let book of books | paginate: { itemsPerPage: 5, currentPage: pageNr, totalItems: totalPages }">
                  <td>{{book.name}}</td>
                  <td>{{book.author}}</td>
                  <td>{{book.isbn}}</td>
                  <td>{{book.total}}</td>
                  <td>{{book.used}}</td>
                  <button type="button" class="btn btn-success" routerLink="/table/{{book.id}}">Deschide</button>
              </tr>
            </table>
            <pagination-template #p="paginationApi"
                    (pageChange)="pageChange?.emit($event)" class="pagination justify-content-end">

                        <div class="pagination-previous page-item " [class.disabled]="p.isFirstPage()">
                            <a class="page-link" *ngIf="!p.isFirstPage()" (click)="p.previous(); getPageInfo(pageNr - 1)"> Inapoi </a>
                        </div>
                
                        <div *ngFor="let page of p.pages page-item" [class.current]="p.getCurrent() === page.value">
                            <a class="page-link" (click)="p.setCurrent(page.value); getPageInfo(page.value)" *ngIf="p.getCurrent() !== page.value">
                                <span class="page-item">{{ page.label }}</span>
                            </a>
                            <div *ngIf="p.getCurrent() === page.value">
                                <span class="page-item active page-link">{{ page.label }}</span>
                            </div>
                        </div>
                
                        <div class="pagination-next page-item" [class.disabled]="p.isLastPage()">
                            <a class="page-link" *ngIf="!p.isLastPage()" (click)="p.next(); getPageInfo(pageNr + 1)"> Inainte </a>
                        </div>
                    
            </pagination-template>
          </div>
      </div>
  </div>
</div>



    <!-- <tr>
        <td>The Two Towers</td>
        <td>J. R. R. Tolkien</td>
        <td>9854535435436</td>
        <td>20</td>
        <td>5</td>
        <button type="button" class="btn btn-success">Deschide</button>
    </tr>
    <tr>
      <td>Front page fatality</td>
      <td>Lyndee Walker</td>
      <td>9654376847574</td>
      <td>40</td>
      <td>6</td>
      <button type="button" class="btn btn-success">Deschide</button>
  </tr>
  <tr>
    <td>The world of abstract art</td>
    <td>Emily Robbins</td>
    <td>9975657584758</td>
    <td>75</td>
    <td>1</td>
    <button type="button" class="btn btn-success">Deschide</button>
</tr>
<tr>
  <td>The fellowship of the ring</td>
  <td>J. R. R. Tolkien</td>
  <td>9145646464364</td>
  <td>50</td>
  <td>30</td>
  <button type="button" class="btn btn-success">Deschide</button>
</tr>
</table>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">Inapoi</a>
      </li>
      <li class="page-item active"><a class="page-link" >1</a></li>
      <li class="page-item"><a class="page-link" >2</a></li>
      <li class="page-item"><a class="page-link" >3</a></li>
      <li class="page-item">
        <a class="page-link" href="#">Inainte</a>
      </li>
    </ul>
  </nav> -->

// frontend_react/src/componets/table.js
import React from "react";
import { Link } from "react-router-dom";
import "./table.css";
import { getBooks } from "../services/bookService";
import Pagination from "react-js-pagination";

class Table extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      error: null,
      isLoaded: false,
      books: [],
      genresFilter: [],
      isBook: true,
      isAuthor: false,
      filter: "",
      activePage: 1,
      totalPages: 0,
    };

    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  componentDidMount() {
    getBooks(
      1,
      this.state.filter,
      this.state.isBook,
      this.state.isAuthor,
      this.state.genresFilter
    ).then(
      (result) => {
        console.log(result);
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].count,
          });
        }
        console.log(result);
        this.setState({
          isLoaded: true,
          books: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  handlePageChange(pageNumber) {
    console.log(`active page is ${pageNumber}`);
    this.setState({ activePage: pageNumber });
    getBooks(
      pageNumber,
      this.state.filter,
      this.state.isBook,
      this.state.isAuthor,
      this.state.genresFilter
    ).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].count,
          });
        }
        this.setState({
          isLoaded: true,
          books: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  handleChange(event) {
    const target = event.target;
    const value = target.value;
    const name = target.name;
    console.log(name);
    console.log(value);
    this.setState({ [name]: value });
  }

  handleOptionChange(event) {
    console.log(event.target.value);
    if (event.target.value === "book") {
      this.setState({
        isBook: true,
        isAuthor: false,
      });
    } else {
      this.setState({
        isBook: false,
        isAuthor: true,
      });
    }
  }

  handleSubmit(event) {
    getBooks(
      1,
      this.state.filter,
      this.state.isBook,
      this.state.isAuthor,
      this.state.genresFilter
    ).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].count,
          });
        }
        console.log(result);
        this.setState({
          isLoaded: true,
          books: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  render() {
    const { error, isLoaded, books } = this.state;
    if (error) {
      return <div>Error: {error.message}</div>;
    } else if (!isLoaded) {
      return <div>Loading...</div>;
    } else {
      return (
        <div className="page-up-margin">
          <div className="container-fluid">
            <div className="row">
              <div className="col-md-8 offset-md-2">
                <div className="input-group md-form form-sm form-2 pl-0 margin">
                  <input
                    className="form-control my-0 py-1 amber-border"
                    type="text"
                    placeholder="Search"
                    aria-label="Search"
                    name="filter"
                    value={this.state.filter}
                    onChange={this.handleChange}
                  />
                  <div className="input-group-append">
                    <span
                      className="input-group-text amber lighten-3"
                      id="basic-text1"
                    >
                      <i
                        className="fas fa-search"
                        onClick={this.handleSubmit}
                        aria-hidden="true"
                      ></i>
                    </span>
                  </div>
                  <span
                    className="align-middle"
                    onChange={this.handleOptionChange.bind(this)}
                  >
                    <input
                      type="radio"
                      name="secondFilter"
                      value="book"
                      checked={this.state.isBook}
                      className="margin-between"
                      className="margin-between"
                    />
                    <label for="male">Carte</label>
                    <input
                      type="radio"
                      name="secondFilter"
                      value="author"
                      checked={this.state.isAuthor}
                      className="margin-between"
                    />
                    <label for="female">Autor</label>
                  </span>
                </div>
              </div>
              <div className="col-md-8 offset-md-2">
                <table className="table table-striped custab">
                  <thead>
                    <th>Carte</th>
                    <th>Autor</th>
                    <th>ISBN</th>
                    <th>Exemplare totale</th>
                    <th>Exemplare in uz</th>
                    <th>Detinatori curenti</th>
                  </thead>
                  {books.map((book) => (
                    <tr key={book}>
                      <td>{book.name}</td>
                      <td>{book.author}</td>
                      <td>{book.isbn}</td>
                      <td>{book.total}</td>
                      <td>{book.used}</td>
                      <Link to={`/table/${book.id}`}>
                        <button
                          type="button"
                          className="btn btn-success"
                          routerLink="/table/{{book.id}}"
                        >
                          Deschide
                        </button>
                      </Link>
                    </tr>
                  ))}
                </table>
                <div className="d-flex justify-content-end">
                  <Pagination
                    prevPageText="Inapoi"
                    nextPageText="Inainte"
                    activePage={this.state.activePage}
                    itemsCountPerPage={5}
                    totalItemsCount={this.state.totalPages}
                    onChange={this.handlePageChange.bind(this)}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      );
    }
  }
}

export default Table;
