// frontend_react/src/componets/login.js
import React from "react";
import "./login.css";
import { login } from "../services/userService";

class Login extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      name: "",
      password: 0,
    };

    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleChange(event) {
    const target = event.target;
    const value = target.value;
    const name = target.name;
    this.setState({ [name]: value });
  }

  handleSubmit(event) {
    login({ username: this.state.name, password: this.state.password }).then(
      (result) => {
        console.log(result.message);
        if (result.message === "Date false") {
          alert("date gresite");
        } else {
          localStorage.setItem("loggedIn", JSON.stringify(true));
          this.props.updateLoggedInStatus();
        }
      },
      (error) => {
        console.log(error);
      }
    );

    event.preventDefault();
  }

  render() {
    return (
      <div className="container-fluid page-up-margin">
        <div className="row">
          <div className="col-md-2 offset-md-5">
            <form onSubmit={this.handleSubmit} className="text-format">
              <div className="form-group">
                <label>
                  Nume:
                  <input
                    type="text"
                    name="name"
                    value={this.state.name}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
              </div>
              <div className="form-group">
                <label>
                  Parola:
                  <input
                    type="password"
                    name="password"
                    value={this.state.value}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
              </div>
              <div className="text-center">
                <input
                  type="submit"
                  value="Trimite"
                  className="btn btn-primary"
                />
              </div>
            </form>
          </div>
        </div>
      </div>
    );
  }
}

export default Login;

// FrontEndAngular/src/app/content/login/login.component.ts
import { Component, OnInit } from "@angular/core";
import { Router } from "@angular/router";
import { UsersService } from "src/app/services/users.service";
import { LoginService } from "src/app/services/login.service";

@Component({
  selector: "app-login",
  templateUrl: "./login.component.html",
  styleUrls: ["./login.component.css"],
})
export class LoginComponent implements OnInit {
  public name: string;
  public password: string;
  constructor(
    private router: Router,
    private user: UsersService,
    private auth: LoginService
  ) {}

  ngOnInit(): void {
    this.name = "cucuc";
    this.password = "micii";
  }

  submit(form) {
    localStorage.setItem("name", form.value.name);
    localStorage.setItem("password", form.value.password);
    this.user
      .login({ username: form.value.name, password: form.value.password })
      .subscribe(
        (res) => {
          console.log(res);
          localStorage.setItem("logged", JSON.stringify(true));
          this.auth.setAuth();
          this.router.navigate([""]);
        },
        (err) => {
          alert("date gresite");
          console.log(err);
        }
      );
  }
}

<div style="margin-top: 2%;">
  <div class="col-md-4 offset-md-4">
    <form #form="ngForm" (ngSubmit)="submit(form)">
      <div class="form-group">
        <label for="name">Nume</label>
        <input
          required
          minlength="5"
          ngModel
          name="name"
          #name="ngModel"
          id="name"
          type="text"
          class="form-control input-md"
        />
      </div>

      <div class="form-group">
        <label for="password">Parola</label>
        <input
          required
          minlength="5"
          ngModel
          name="password"
          #password="ngModel"
          type="password"
          id="password"
          class="form-control input-md"
        />
      </div>

      <div class="text-center">
        <button class="btn btn-primary">
          Trimite
        </button>
      </div>
    </form>
  </div>
</div>
