// frontend_react/src/componets/user-add.js
import React from "react";
import "./user-add.css";
import { addUser } from "../services/userService";

class UserAdd extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      name: "",
      cnp: "",
    };

    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleChange(event) {
    const target = event.target;
    const value = target.value;
    const name = target.name;
    this.setState({ [name]: value });
  }

  handleSubmit(event) {
    addUser({ name: this.state.name, cnp: this.state.cnp }).then((result) => {
      this.props.history.push("/users");
    });
    event.preventDefault();
  }

  render() {
    return (
      <div className="container-fluid page-up-margin">
        <div className="row">
          <div className="col-md-2 offset-md-5">
            <form onSubmit={this.handleSubmit}>
              <div className="form-group">
                <label>
                  Nume:
                  <input
                    type="text"
                    name="name"
                    value={this.state.name}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
              </div>
              <div className="form-group">
                <label>
                  CNP:
                  <input
                    type="text"
                    name="cnp"
                    value={this.state.value}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
              </div>
              <div className="text-center">
                <input
                  type="submit"
                  value="Trimite"
                  className="btn btn-primary"
                />
              </div>
            </form>
          </div>
        </div>
      </div>
    );
  }
}

export default UserAdd;

// FrontEndAngular/src/app/content/users/user-add/user-add.component.ts
import { Component, OnInit, Output, EventEmitter } from "@angular/core";
import { UsersService } from "src/app/services/users.service";
import { Router } from "@angular/router";

@Component({
  selector: "app-user-add",
  templateUrl: "./user-add.component.html",
  styleUrls: ["./user-add.component.css"],
})
export class UserAddComponent implements OnInit {
  constructor(private user: UsersService, private router: Router) {}

  ngOnInit(): void {}

  submit(form) {
    this.user.addUser(form.value).subscribe(
      (res) => {
        this.router.navigate(["../../../users"]);
      },
      (err) => {}
    );
  }
}

<div class="col-md-4 offset-md-4">
  <form #form="ngForm" (ngSubmit)="submit(form)">
    <div class="form-group">
      <label for="lastName">Nume</label>
      <input
        required
        minlength="5"
        ngModel
        name="name"
        #name="ngModel"
        id="name"
        type="text"
        class="form-control input-md"
      />
      <div class="alert alert-danger" *ngIf="name.touched && !name.valid">
        <div *ngIf="name.errors.required">
          Numele is required !
        </div>
        <div *ngIf="name.errors.minlength">
          The name should be minimum
          {{ name.errors.minlength.requiredLength }} characters !
        </div>
      </div>
    </div>

    <div class="form-group">
      <label for="firstName">CNP</label>
      <input
        required
        minlength="10"
        ngModel
        name="cnp"
        #cnp="ngModel"
        type="text"
        id="cnp"
        class="form-control input-md"
      />
      <div class="alert alert-danger" *ngIf="cnp.touched && !cnp.valid">
        <div *ngIf="cnp.errors.required">
          Prenumele is required !
        </div>
        <div *ngIf="cnp.errors.minlength">
          The cnp should be minimum
          {{ cnp.errors.minlength.requiredLength }} characters !
        </div>
      </div>
    </div>

    <div class="text-center">
      <button class="btn btn-primary">
        Submit
      </button>
    </div>
  </form>
</div>
