// frontend_react/src/componets/user-edit.js
import React from "react";
import "./user-edit.css";
import { getUserById, editUserById } from "../services/userService";

class UserEdit extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      name: "",
      cnp: 0,
    };
    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  componentDidMount() {
    getUserById(this.props.match.params.id).then(
      (result) => {
        this.setState({
          isLoaded: true,
          name: result.name,
          cnp: result.cnp,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
    console.log(this.props.match.params.id);
  }

  handleChange(event) {
    const target = event.target;
    const value = target.value;
    const name = target.name;
    this.setState({ [name]: value });
  }

  handleSubmit(event) {
    editUserById(this.props.match.params.id, {
      name: this.state.name,
      cnp: this.state.cnp,
    }).then((result) => {
      this.props.history.push("/users");
    });
    console.log(this.props.history);

    event.preventDefault();
  }

  render() {
    return (
      <div className="container page-up-margin">
        <div className="row">
          <div className="offset-md-5">
            <form onSubmit={this.handleSubmit}>
              <div className="form-group">
                <label>
                  Nume:
                  <input
                    type="text"
                    name="name"
                    value={this.state.name}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
              </div>
              <div className="form-group">
                <label>
                  CNP:
                  <input
                    type="text"
                    name="cnp"
                    value={this.state.cnp}
                    onChange={this.handleChange}
                    className="form-control input-md"
                  />
                </label>
              </div>
              <div className="text-center">
                <input
                  type="submit"
                  value="Trimite"
                  className="btn btn-primary"
                />
              </div>
            </form>
          </div>
        </div>
      </div>
    );
  }
}

export default UserEdit;

// FrontEndAngular/src/app/content/users/user-edit/user-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { UsersService } from 'src/app/services/users.service';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-user-edit',
  templateUrl: './user-edit.component.html',
  styleUrls: ['./user-edit.component.css']
})
export class UserEditComponent implements OnInit {
  name = 'hari';
  data;
  cnp;
  userId;
  constructor(private user: UsersService, private route:ActivatedRoute, private router:Router) { }

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.userId = params['id'];
    })

    this.user.getUserById(this.userId).subscribe(response=>{
      this.data = response;
      this.name = this.data.name;
      this.cnp = this.data.cnp;
    })
  }
  submit(form){
    this.name = form.value.name;
    this.cnp = form.value.cnp;
    this.user.editUserById({name: this.name, cnp: this.cnp}, this.userId).subscribe(
      res=>{ 
        console.log(res);
         this.router.navigate(['../../../users'])
      },
      err=>{ console.log(err)}
    )
  }

}

<div style="margin-top: 2%">
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-6 offset-md-3">

<form #form="ngForm" (ngSubmit)="submit(form)">
    <div class="form-group ">
        <label for="lastName">Nume</label>
        <input 
            required 
            minlength="5" 
            [(ngModel)] = "name"
            name="name" 
            id="name" 
            type="text" 
            class="form-control input-md">
    </div>

    <div class="form-group">
        <label for="firstName">CNP</label>
        <input 
            required 
            minlength="10" 
            [(ngModel)] = "cnp"
            name="cnp"  
            type="text"
            id="cnp" 
            class="form-control input-md">
    </div>

    <div class="text-center">
        <button class="btn btn-primary">
            Submit
        </button>
    </div>
</form>
</div></div></div></div>
