// frontend_react/src/componets/books.js
import React from "react";
import "./books.css";
import { Link } from "react-router-dom";
import { getBooks, deleteBook } from "../services/bookService";
import Pagination from "react-js-pagination";

class Books extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      error: null,
      isLoaded: false,
      books: [],
      genresFilter: [],
      isBook: true,
      isAuthor: false,
      filter: "",
      activePage: 1,
      totalPages: 0,
    };

    this.deleteBookClicked = this.deleteBookClicked.bind(this);
    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  componentDidMount() {
    getBooks(
      1,
      this.state.filter,
      this.state.isBook,
      this.state.isAuthor,
      this.state.genresFilter
    ).then(
      (result) => {
        console.log(result);
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].count,
          });
        }
        console.log(this.state.totalPages);
        this.setState({
          isLoaded: true,
          books: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  async deleteBookClicked(id) {
    await deleteBook(id);
    getBooks(
      1,
      this.state.filter,
      this.state.isBook,
      this.state.isAuthor,
      this.state.genresFilter
    ).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].count,
          });
        }
        this.setState({
          isLoaded: true,
          books: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  handlePageChange(pageNumber) {
    console.log(`active page is ${pageNumber}`);
    this.setState({ activePage: pageNumber });
    getBooks(
      pageNumber,
      this.state.filter,
      this.state.isBook,
      this.state.isAuthor,
      this.state.genresFilter
    ).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].count,
          });
        }
        this.setState({
          isLoaded: true,
          books: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  handleChange(event) {
    const target = event.target;
    const value = target.value;
    const name = target.name;
    console.log(name);
    console.log(value);
    this.setState({ [name]: value });
  }

  handleOptionChange(event) {
    console.log(event.target.value);
    if (event.target.value === "book") {
      this.setState({
        isBook: true,
        isAuthor: false,
      });
    } else {
      this.setState({
        isBook: false,
        isAuthor: true,
      });
    }
  }

  handleSubmit(event) {
    getBooks(
      1,
      this.state.filter,
      this.state.isBook,
      this.state.isAuthor,
      this.state.genresFilter
    ).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].count,
          });
        }
        console.log(result);
        this.setState({
          isLoaded: true,
          books: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  render() {
    const { error, isLoaded, books } = this.state;
    if (error) {
      return <div>Error: {error.message}</div>;
    } else if (!isLoaded) {
      return <div>Loading...</div>;
    } else {
      return (
        <div className="page-up-margin">
          <div className="container-fluid">
            <div className="row">
              <div className="col-md-8 offset-md-2">
                <div className="input-group md-form form-sm form-2 pl-0 margin">
                  <input
                    className="form-control my-0 py-1 amber-border"
                    type="text"
                    placeholder="Search"
                    aria-label="Search"
                    name="filter"
                    value={this.state.filter}
                    onChange={this.handleChange}
                  />
                  <div className="input-group-append">
                    <span
                      className="input-group-text amber lighten-3"
                      id="basic-text1"
                    >
                      <i
                        className="fas fa-search"
                        onClick={this.handleSubmit}
                        aria-hidden="true"
                      ></i>
                    </span>
                    <span
                      className="align-middle"
                      onChange={this.handleOptionChange.bind(this)}
                    >
                      <input
                        type="radio"
                        name="secondFilter"
                        value="book"
                        checked={this.state.isBook}
                        className="margin-between"
                      />
                      <label for="book">Carte</label>
                      <input
                        type="radio"
                        name="secondFilter"
                        value="author"
                        checked={this.state.isAuthor}
                        className="margin-between"
                      />
                      <label for="author">Autor</label>
                    </span>
                  </div>
                </div>
                <table className="table">
                  <thead className="thead-light">
                    <th>Nume</th>
                    <th>Autor</th>
                    <th>Exemplare</th>
                    <th>Opiuni</th>
                  </thead>
                  {books.map((book) => (
                    <tbody key={book.name}>
                      <tr>
                        <td>{book.name} </td>
                        <td>{book.author}</td>
                        <td>{book.total}</td>
                        <td>
                          <Link to={`/books/edit/${book.id}`}>
                            <button
                              type="button"
                              className="btn btn-sm btn-info"
                              id="edit"
                            >
                              Edit
                            </button>
                          </Link>
                          <button
                            onClick={() => this.deleteBookClicked(book.id)}
                            type="button"
                            className="btn btn-sm btn-danger"
                            id="edit"
                          >
                            Delete
                          </button>
                        </td>
                      </tr>
                    </tbody>
                  ))}
                </table>
                <div className="d-flex justify-content-end">
                  <Pagination
                    prevPageText="Inapoi"
                    nextPageText="Inainte"
                    activePage={this.state.activePage}
                    itemsCountPerPage={5}
                    totalItemsCount={this.state.totalPages}
                    onChange={this.handlePageChange.bind(this)}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      );
    }
  }
}

export default Books;

// FrontEndAngular/src/app/content/books/books.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { BooksService } from 'src/app/services/books.service';

@Component({
  selector: 'app-books',
  templateUrl: './books.component.html',
  styleUrls: ['./books.component.css']
})
export class BooksComponent implements OnInit {
  @Input() id: string;
  @Input() maxSize: number;
  @Output() pageChange: EventEmitter<number>;
  @Output() pageBoundsCorrection: EventEmitter<number>;
  add = false;
  edit = false;
  books;
  pageNr: number = 1;
  filter: boolean = true;
  isBook = true;
  isAuthor = false;
  totalPages;

  query = {
    book: true,
    author: false,
    search: '',
    genres: []
  }
  constructor(private book: BooksService) { }

  ngOnInit(): void {
    this.getBookData()
  }

  addToggle(){
    this.add = !this.add;
    this.edit = false;
  }

  editToggle(){
    this.edit = true;
    this.add = false;
  }

  delete(){

  }

  getPageInfo(nr:number){
    this.pageNr = nr;
    this.getBookData();
  }
  receiveMessage($event) {
    this.query.search = $event;
    
    this.getBookData();
  }

  receiveFilter($event) {
    
    this.filter = $event
    if (this.filter === true){
      this.isBook = true;
      this.isAuthor = false;
    }
    else{
      this.isBook = false;
      this.isAuthor = true;
    }
    this.pageNr = 1;
    this.query.book = this.isBook;
    this.query.author = this.isAuthor;
  }
  getBookData(){
    this.book.getBooks(this.pageNr, this.query.search, this.query.book, this.query.author, this.query.genres).subscribe(response =>{
    this.books = response;
    console.log(this.books);
    this.totalPages =  0;
      if(Object.keys(response).length){
        
        this.totalPages = response[0].count
        console.log(this.totalPages);
      }
  })
  }

  deleteBook(id){
    this.book.deleteBook(id).subscribe(
      res=>{this.getBookData(); console.log('deleted')},
      err=>{}
    )
  }

  receiveRefresh($event) {
    this.getBookData();
  }
}

<div style="margin-top: 2%">
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-5 offset-md-2">
                <app-search (messageEvent)="receiveMessage($event)" (radioEvent)="receiveFilter($event)"></app-search>
                
                <table class="table">
                    <thead class="thead-light">
                        <button type="button" class="btn btn-sm btn-success align-right" id="add" (click)='addToggle()'>
                            Add
                        </button>
                        <tr>
                            <th>Nume</th>
                            <th>Autor</th>
                            <th>Exemplare</th>
                            <th>Opiuni</th>
                        </tr>   
                    </thead>
                    <tbody>
                        <tr *ngFor="let book of books | paginate: { itemsPerPage: 5, currentPage: pageNr, totalItems: totalPages }">
                            <td>{{book.name}}</td>
                            <td>{{book.author}}</td>
                            <td>{{book.total}}</td>
                            <td>
                                <button type="button" class="btn btn-sm btn-info" id="edit" routerLink="edit/{{book.id}}">
                                    Edit
                                </button>
                                <button type="button" class="btn btn-sm btn-danger" id="edit" (click)="deleteBook(book.id)">
                                    Delete
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <pagination-template #p="paginationApi"
                    (pageChange)="pageChange?.emit($event)" class="pagination justify-content-end">

                        <div class="pagination-previous page-item " [class.disabled]="p.isFirstPage()">
                            <a class="page-link" *ngIf="!p.isFirstPage()" (click)="p.previous(); getPageInfo(pageNr - 1)"> Inapoi </a>
                        </div>
                
                        <div *ngFor="let page of p.pages page-item" [class.current]="p.getCurrent() === page.value">
                            <a class="page-link" (click)="p.setCurrent(page.value); getPageInfo(page.value)" *ngIf="p.getCurrent() !== page.value">
                                <span class="page-item">{{ page.label }}</span>
                            </a>
                            <div *ngIf="p.getCurrent() === page.value">
                                <span class="page-item active page-link">{{ page.label }}</span>
                            </div>
                        </div>
                
                        <div class="pagination-next page-item" [class.disabled]="p.isLastPage()">
                            <a class="page-link" *ngIf="!p.isLastPage()" (click)="p.next(); getPageInfo(pageNr + 1)"> Inainte </a>
                        </div>
                    
                </pagination-template>
            </div>

            <div class="col-md-3" *ngIf="add">
                <app-books-add (refreshEvent)="receiveRefresh($event)"></app-books-add>
            </div>

        </div>
    </div>
</div>
