// frontend_react/src/componets/users.js
import React from "react";
import "./users.css";
import { Link } from "react-router-dom";
import Pagination from "react-js-pagination";
import { getUsers, deleteUser } from "../services/userService";

class Users extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      error: null,
      isLoaded: false,
      items: [],
      filter: "",
      activePage: 1,
      totalPages: 0,
    };
    this.deleteUserClicked = this.deleteUserClicked.bind(this);
    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  componentDidMount() {
    getUsers(this.state.activePage, this.state.filter).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].total,
          });
        }
        console.log(result);
        this.setState({
          isLoaded: true,
          items: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  async deleteUserClicked(id) {
    await deleteUser(id);
    getUsers(1, this.state.filter).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].total,
          });
        }
        console.log(result);
        this.setState({
          isLoaded: true,
          items: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  handlePageChange(pageNumber) {
    console.log(`active page is ${pageNumber}`);
    this.setState({ activePage: pageNumber });
    getUsers(pageNumber, this.state.filter).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].total,
          });
        }
        console.log(result);
        this.setState({
          isLoaded: true,
          items: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  handleChange(event) {
    const target = event.target;
    const value = target.value;
    const name = target.name;
    this.setState({ [name]: value });
  }

  handleSubmit(event) {
    getUsers(1, this.state.filter).then(
      (result) => {
        this.setState({
          totalPages: 0,
        });
        if (Object.keys(result).length) {
          this.setState({
            totalPages: result[0].total,
          });
        }
        console.log(result);
        this.setState({
          isLoaded: true,
          items: result,
        });
      },
      (error) => {
        this.setState({
          isLoaded: true,
          error,
        });
      }
    );
  }

  render() {
    const { error, isLoaded, items } = this.state;
    if (error) {
      return <div>Error: {error.message}</div>;
    } else if (!isLoaded) {
      return <div>Loading...</div>;
    } else {
      return (
        <div className="page-up-margin">
          <div className="container-fluid">
            <div className="row">
              <div className="col-md-8 offset-md-2">
                <div className="input-group md-form form-sm form-2 pl-0 margin">
                  <input
                    className="form-control my-0 py-1 amber-border"
                    type="text"
                    placeholder="Search"
                    aria-label="Search"
                    name="filter"
                    value={this.state.filter}
                    onChange={this.handleChange}
                  />
                  <div className="input-group-append">
                    <span
                      className="input-group-text amber lighten-3"
                      id="basic-text1"
                    >
                      <i
                        className="fas fa-search"
                        onClick={this.handleSubmit}
                        aria-hidden="true"
                      ></i>
                    </span>
                  </div>
                </div>
                <table className="table">
                  <thead className="thead-light">
                    <th>Nume</th>
                    <th>CNP</th>
                    <th>Carti</th>
                    <th>Opiuni</th>
                  </thead>
                  {items.map((user) => (
                    <tbody key={user.name}>
                      <tr>
                        <td>{user.name} </td>
                        <td>{user.cnp}</td>
                        <td>
                          {user.books.map((book) => (
                            <div>{book}</div>
                          ))}
                        </td>
                        <td>
                          <Link to={`/users/edit/${user.id}`}>
                            <button
                              type="button"
                              className="btn btn-sm btn-info"
                              id="edit"
                            >
                              Edit
                            </button>
                          </Link>
                          <button
                            onClick={() => this.deleteUserClicked(user.id)}
                            type="button"
                            className="btn btn-sm btn-danger"
                            id="edit"
                          >
                            Delete
                          </button>
                        </td>
                      </tr>
                    </tbody>
                  ))}
                </table>
                <div className="d-flex justify-content-end">
                  <Pagination
                    prevPageText="Inapoi"
                    nextPageText="Inainte"
                    activePage={this.state.activePage}
                    itemsCountPerPage={7}
                    totalItemsCount={this.state.totalPages}
                    onChange={this.handlePageChange.bind(this)}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      );
    }
  }
}

export default Users;

// FrontEndAngular/src/app/content/users/users.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from "@angular/core";
import { Router } from "@angular/router";
import { UsersService } from "src/app/services/users.service";

@Component({
  selector: "app-users",
  templateUrl: "./users.component.html",
  styleUrls: ["./users.component.css"],
})
export class UsersComponent implements OnInit {
  @Input() id: string;
  @Input() maxSize: number;
  @Output() pageChange: EventEmitter<number>;
  @Output() pageBoundsCorrection: EventEmitter<number>;

  add = false;
  edit = false;
  href: string = "";
  book = true;
  users;
  pageNr: number = 1;
  totalNr: number;
  message: string = "";
  constructor(private router: Router, private user: UsersService) {}

  ngOnInit(): void {
    this.href = this.router.url;
    if (this.href === "/table") this.book = false;
    else {
      this.book = true;
    }

    this.getUserData();
  }

  receiveMessage($event) {
    this.message = $event;
    this.pageNr = 1;
    this.getUserData();
  }

  addToggle() {
    this.add = !this.add;
    this.edit = false;
  }

  editToggle() {
    this.edit = true;
    this.add = false;
  }

  delete() {}

  getPageInfo(nr: number) {
    this.pageNr = nr;
    this.getUserData();
  }

  getUserData() {
    this.user.getUsers(this.pageNr, this.message).subscribe((response) => {
      this.users = response;
      this.totalNr = 0;
      if (Object.keys(response).length) {
        this.totalNr = response[0].total;
        console.log(this.totalNr);
      }
    });
  }

  deleteUser(id) {
    this.user.deleteUser(id).subscribe(
      (res) => {
        this.getUserData();
      },
      (err) => {}
    );
  }
}

<div style="margin-top: 2%;">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <app-search (messageEvent)="receiveMessage($event)"></app-search>
        <table class="table">
          <thead class="thead-light">
            <th>Nume</th>
            <th>CNP</th>
            <th>Carti</th>
            <th>Opiuni</th>
          </thead>
          <tbody *ngIf="book">
            <tr
              *ngFor="
                let user of users
                  | paginate
                    : {
                        itemsPerPage: 7,
                        currentPage: pageNr,
                        totalItems: totalNr
                      }
              "
            >
              <td>{{ user.name }}</td>
              <td>{{ user.cnp }}</td>
              <td>
                <div *ngFor="let book of user.books">{{ book }}</div>
              </td>
              <td>
                <button
                  type="button"
                  class="btn btn-sm btn-info"
                  id="edit"
                  routerLink="edit/{{ user.id }}"
                >
                  Edit
                </button>
                <button
                  type="button"
                  class="btn btn-sm btn-danger"
                  id="edit"
                  (click)="deleteUser(user.id)"
                >
                  Delete
                </button>
              </td>
            </tr>
          </tbody>
        </table>

        <pagination-template
          #p="paginationApi"
          (pageChange)="pageChange?.emit($event)"
          class="pagination justify-content-end"
        >
          <div
            class="pagination-previous page-item"
            [class.disabled]="p.isFirstPage()"
          >
            <a
              class="page-link"
              *ngIf="!p.isFirstPage()"
              (click)="p.previous(); getPageInfo(pageNr - 1)"
            >
              Inapoi
            </a>
          </div>

          <div
            *ngFor="let page of p.pages; &quot;page-item&quot;"
            [class.current]="p.getCurrent() === page.value"
          >
            <a
              class="page-link"
              (click)="p.setCurrent(page.value); getPageInfo(page.value)"
              *ngIf="p.getCurrent() !== page.value"
            >
              <span class="page-item">{{ page.label }}</span>
            </a>
            <div *ngIf="p.getCurrent() === page.value">
              <span class="page-item active page-link">{{ page.label }}</span>
            </div>
          </div>

          <div
            class="pagination-next page-item"
            [class.disabled]="p.isLastPage()"
          >
            <a
              class="page-link"
              *ngIf="!p.isLastPage()"
              (click)="p.next(); getPageInfo(pageNr + 1)"
            >
              Inainte
            </a>
          </div>
        </pagination-template>
      </div>
    </div>
  </div>
</div>
